# Generated by Django 2.2.2 on 2020-02-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200228_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
