# Generated by Django 2.2.2 on 2020-02-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200228_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_date',
        ),
    ]
