# Generated by Django 2.2.2 on 2020-02-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
    ]
